In [ ]:
string = "This is a centered string"
string2 = "Another string"

alnum = "23adsfa"
old = "is"
new = "was"
sub = "This"

# Operators
string + string2  # Concatenate 2 strings together.
string * 2  # Repeat the string 2 times.

# Length
len(string)  # Returns the length of the string

# Searching elements
string.find('st')  # Returns the first occurrence of the specified substring
# Returns the number of occurrences of the specified substring
string.count('t')

# Casing of characters
string.lower()  # Returns all lower case characters
string.upper()  # Returns all upper case characters
string.title()  # Capitalizes each word in a string
string.capitalize()  # Capitalizes first letter in the string.

# String Manipulation
string.replace(old, new)  # Replaces all occurrences of the specified substring

# Check conditions
# Contains only alphabetic and numeric characters (not even space).
string.isalnum()
string.isalpha()  # Contains only alphabetic characters
string.isdigit()  # Contains only numeric characters
string.islower()  # Check if string is lower case
string.isupper()  # Check if string is upper case
string.startswith(sub)  # Check if string starts with a substring
string.endswith(sub)  # Check if string starts with a substring
sub in string  # Check if string contains a substring

# Splitting string
string = "1 2 3 4 5"
string.split(" ")

# Store multiple numbers separated by spaces in a list
list(map(int, string.split(" ")))

print(string)


In [ ]:
string = "Milwaukee"

#   M   i   l   w   a   u   k   e   e
#   0   1   2   3   4   5   6   7   8
#  -9  -8  -7  -6  -5  -4  -3  -2  -1

string[1:]      # ilwaukee  : start at 1 till the end of string
# iw        : start at 1 till 4 (excluding 5) and skip till the 2nd element
string[1:5:2]
# ia        : start at 1 till 4 (excluding 5) and skip till the 3rd element
string[1:5:3]
string[:3]      # Mil : start at 0 till 2 (excluding 3)
# wk : Start at -6 till -2 (excluding -1) and skip till the 3rd element
string[-6:-1:3]
string[-5:5]    # a : Start at -5 till 4 (excluding 5)
# Empty : There are no elements between 5 and 3 since 5 is greater.
string[5:-5]
string[1:-5]    # ilw : start from 1 till -4 (excluding -5)


In [ ]:
import re  # first import re

string = "This is a string"


In [ ]:
import re

pattern = "[\w\d]+@[\w]+\.[\w]{2,3}"  # Check for email
# Emails contains 1 or more characters which could be alphabets (\w) or numbers(\d).
# Then they have @ (at) symbol followed by the domain name which again contains alphabets
# Then there is the period symbol (.) followed by the domain name consisting of 2-3 characters max.

# Check for password
pattern = "^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\w\d\s])([^\s]){8,}$"
# This checks that the password is at least 8 characters long {8,}
# It has digits               : (?=.*\d)
# It has Lowercase characters : (?=.*[a-z])
# It has Uppercase Characters : (?=.*[A-Z])
# It has Special Characters   : (?=.*[^\w\d\s])
# Doesn't have spaces         : ([^\s])
# Has min length of 8         : {8,}
# Checks within boundary      : ^ ...  $

pattern = "((\w+:\/\/)[\w\D]+)"  # Check for url
# protocol consisting of words and '://' part  : (\w+:\/\/)
# Then match any characters

print("valid" if re.search(pattern, input()) else "invalid")


In [9]:
# Receive arguments as list. (useful when we're dealing with positional arguments)
def my_func(*args):
    print(args)

# Receive arguments as dictionary. (Used when we're dealing with Keyword arguments')


def my_func(**kwargs):
    print(kwargs)


# Pandas Data Frame


In [1]:
# Creating a data frame using only a list
import pandas as pd

mylist = [1, 2, 3, 4, 5]

df = pd.DataFrame(mylist)

df


0
0  1
1  2
2  3
3  4
4  5

In [2]:
# Creating a list and labeling the Rows

df = pd.DataFrame(mylist, index=["a", "b", "c", "d", "e"])

df


0
a  1
b  2
c  3
d  4
e  5

In [4]:
# Creating a dataframe and also adding column name

df = pd.DataFrame(mylist, index=["a", "b", "c",
                  "d", "e"], columns=["Integers"])

df


Integers
a         1
b         2
c         3
d         4
e         5

In [57]:
# Using zip()

names = ["John", "Finn", "Cody", "Kenny"]
rating = [5, 4, 5, 4]

df = pd.DataFrame(list(zip(names, rating)), columns=['Wrestlers', 'Rating'])

df


[('John', 5), ('Finn', 4), ('Cody', 5), ('Kenny', 4)]

In [13]:
# Using Multi-dimensional List

mylist = [
    ['Tom', 23],
    ['Jon', 43],
    ['Tim', 63],
    ['Vic', 33]
]

df = pd.DataFrame(mylist, columns=['Name', 'Age'])

df

Name  Age
0  Tom   23
1  Jon   43
2  Tim   63
3  Vic   33

In [56]:
import pandas as pd

mydict = {
    'Name': ['UFC', 'WWE', 'NXT', 'AEW'],
    'Roster': ['89', '78', '32', '128'],
    'Year': ['2002', '1970', '2012', '2019']
}

df = pd.DataFrame(mydict, index = ['MMA', 'Mainstream Wrestling', 'Owned', 'Indie'])

df


Name Roster  Year
MMA                   UFC     89  2002
Mainstream Wrestling  WWE     78  1970
Owned                 NXT     32  2012
Indie                 AEW    128  2019

# Numpy


In [15]:

# Creating an array usi
import numpy as np
l1 = [1, 2, 3, 4, 5]
a = np.array(l1)
print(a)


[1 2 3 4 5]


In [17]:
# Creating numpy array using tuple

t1 = (5, 6, 7, 8, 9)
b = np.array(t1)
print(b)


[5 6 7 8 9]


In [18]:
# Create a 2 dimensional array
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Multi-dimensional array using tuple

e = np.array(((11, 12), (13, 14)))
print(e)


[[11 12]
 [13 14]]


In [21]:
# Shape of the array

print(a.shape)
print(b.shape)
print(d.shape)


(5,)
(5,)
(3, 3)


In [22]:
# Getting the dimension of the multi-dimension

print(e.ndim)


2


In [24]:
# Fill the array with Zeroes and Ones

c1 = np.zeros((2, 3))  # 2 Rows, 3 Columns
d1 = np.ones((4, 5))  # 4 Rows, 5 Columns

print(c1)
print(d1)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
# Fill the matrix with value of certain type

c2 = np.zeros((2, 3), dtype=int)
print(c2)


[[0 0 0]
 [0 0 0]]


In [27]:
# Fill the matrix with value of certain type

c3 = np.full((3, 3), 6, dtype=float)
print(c3)


[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [28]:
# scalar operations

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(a)
print(a+10)
print(a*2)
print(a-5)


[1 2 3 4 5 6 7 8]
[11 12 13 14 15 16 17 18]
[ 2  4  6  8 10 12 14 16]
[-4 -3 -2 -1  0  1  2  3]


In [30]:
# arithmetic operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)

print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.dot(A, B))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [31]:
# reshape and flatten
C = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
r = np.reshape(C, (3, 5))

print(r)
print(r.flatten())


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [35]:
# eigen values of a matrix

from numpy import linalg as linal

g = linal.eigvals([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(g)


[ 1.61168440e+01 -1.11684397e+00 -8.58274334e-16]


In [38]:
# transpose

c = a.transpose()
print(c)


[1 2 3 4 5 6 7 8]


In [39]:
# determinant of matrix

n = np.array([[50, 29], [30, 44]])
det = linal.det(n)
print(det)


1330.0000000000002


In [85]:
import numpy as np

# Functions
arr = np.array([[1,2,3],[4,5,6]])
arr.shape
arr.ndim
arr.flatten()
np.zeros((2,3))
np.ones((2,3))
value = 10
np.full((3,3), value, dtype = int)

# Scalar
arr
arr+10
arr*2
arr-5

# Arithmetic
np.add(A, B)
np.subtract(A, B)
np.multiply(A, B)
np.dot(A, B)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
import pandas as pd

list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
a = ['a', 'b', 'c', 'd']
b = [1, 2, 3, 4]

# Creating data frame
df = pd.read_csv("file.txt")
df = pd.DataFrame(list1)
df = pd.DataFrame(list(zip(a, b))) # Specify index and columns


In [54]:
try:
    print(2/0)
except:
    print("Exception : You divided by Zero")
else:
    print("If this code executes, there were no exceptions.")
finally:
    print("This statement is always executed whether the exception occurred or not.")


{'name': 'Priyanshu'}


In [77]:
# Conversions
print(int("110", 2)) # Binary to decimal
print(bin(5)) # Decimal to Binary
print(oct(18)) # Decimal to octal
print(hex(17)) # Decimal to hex

print(ord("9")) # Get ascii value
print(chr(57)) # Print character using ascii value


6
0b101
0o22
0x11
57
9
